name: Languages card

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: Slush97
          UTC_OFFSET: -8
          EXCLUDE: HTML,CSS,TeX,Dockerfile,Makefile,Jupyter Notebook,SCSS,Shell,Batchfile
